language: python
python:
  - "3.6"

install:            # Install requirement as "Environment Setup Section"
  - pip install casadi numpy scipy sobol_seq matplotlib networkx
matrix:
  include:
    - name: "DOC"
      python: "3.6"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install -r docs/requirements.txt
      script:
        - cd docs/
        - make html
        - cd -
      deploy:              # deploy to github page
        - provider: pages
          skip_cleanup: true
          local_dir: docs/build/html
          github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    - name: "TEST_36"
      python: "3.6"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install codecov nose
      # Run the unit test
      script:
        - cd unit_tests
        - nosetests --with-coverage
        #- coverage run tests.py
      # Push the results back to codecov
      after_success:
        - codecov
    - name: "TEST_27"
      python: "2.7"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install codecov nose mock
      # Run the unit test
      script:
        - cd unit_tests
        - nosetests --with-coverage
        #- coverage run tests.py
      # Push the results back to codecov
      after_success:
        - codecov