language: python
python:
  - "3.6"

install:            # Install requirement as "Environment Setup Section"
  - pip install casadi numpy scipy sobol_seq matplotlib networkx
matrix:
  include:
    # Documentaiton
    - name: "DOC"
      python: "3.8"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install -r docs/requirements.txt
      script:
        - cd docs/
        - make html
        - cd -
      deploy:              # deploy to github page
        - provider: pages
          skip_cleanup: true
          local_dir: docs/build/html
          github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
          on:
            branch: master
    # Run unittests in Python 3.6
    - name: "TEST_36"
      python:
        - "3.6"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install codecov nose
      # Run the unit test
      script:
        - pytest --cov=yaocptool/
    # Run unittests in Python 3.7
    - name: "TEST_37"
      python:
        - "3.7"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install codecov nose
      # Run the unit test
      script:
        - pytest --cov=yaocptool/
    # Run unittests in Python 3.8
    - name: "TEST_38"
      python:
        - "3.8"
      install:
        - pip install casadi numpy scipy sobol_seq matplotlib networkx
        - pip install codecov nose
      # Run the unit test
      script:
        - pytest --cov=yaocptool/
      # Push the results back to codecov
      after_success:
        - codecov
    # Install in Python3.6
    - name: "INSTALL_38"
      python: "3.8"
      script:
        - pip install .
        - python -c 'from __future__ import print_function; import sys; sys.path.remove(""); import yaocptool; print(yaocptool)'

